config/routes.rb
Rails.application.routes.draw do
  resources :live_searches
  get 'groups/index'
  get 'groups/show'
  post 'groups/show'
  get 'groups/new'
  post 'groups/join'
  post 'groups/leave'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  get 'contact_us/index'
  get 'users/new'
  get 'privacy_policy/index'
  get 'terms_of_service/index'
  get 'about/index'

  #get '/borrow_reauests'
  get 'home/index'

  # Session routes
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # Users routes
  resources :users do
    resources :settings , only: [:index, :destroy]
    resources :password_changes, only: [:new, :create]
  end

  #Review routes
  resources :people do
    resources :comments
  end
  resources :users do
    resources :comments
  end

  resources :listings do
    resources :comments
  end
  resources :comments do
    resources :comments
  end

  #Private messaging routes
  mount ActionCable.server => '/cable'

  resources :chatrooms
  resources :messages

  # Account Activation routes
  resources :account_activations, only: [:edit]

  # Password Reset Routes
  resources :password_resets, only: [:new,:create,:edit,:update]

  # Listing routes
  resources :listings

  # Groups routes
  resources :groups
  get :join, controller: :groups
  get :leave, controller: :groups
  post '/groups/join', to: 'group#join'
  post '/groups/leave', to: 'group#leave'

  # Search routes
  get :autocomplete_users, controller: :users
  get :autocomplete_listings, controller: :listings
  get :autocomplete_groups, controller: :groups
  get :autocomplete_add_to_groups, controller: :groups
  get '/search_users', to: 'users#search_users'
  get '/search_listings', to: 'listings#search_listings'
  get '/search_groups', to: 'groups#search_groups'
  get '/search_add_to_groups', to: 'groups#search_add_to_groups'
  get '/add_to_group/:user_id', to: 'groups#add_to_group', as: 'add_to_group'

  # Location routes
  resources :locations

  # Report routes (for listings)
  get '/listings/:id/report', to: 'listings#report', as: 'report_listing'
  get '/reports/delete_listing_and_request/:id', to: 'reports#delete_listing_and_request', as: 'delete_report_listing'
  get '/reports/delete_request/:id', to: 'reports#delete_request', as: 'delete_report_request'

  # Report routes (for users)
  get '/users/:id/report', to: 'users#report', as: 'report_user'
  get '/user_report/delete_request/:id', to: 'user_report#delete_request', as: 'delete_user_report_request'

  # resources :borrow_requests
  # get :requested_listings, controller: :borrow_requests
  # get :need_approval, controller: :borrow_requests

  get '/borrow_requests/:listing_id', to: 'borrow_requests#send_request', as: 'create_borrow_request'
  patch 'borrow_request/:id', to: 'borrow_requests#approve', as: 'borrow_approve'
  get '/borrow_request/:id', to: 'borrow_requests#decline', as: 'borrow_decline'
  delete '/borrow_request/:id', to: 'borrow_requests#delete_request', as: 'borrow_delete'
  put '/borrow_request/:id', to: 'borrow_requests#update', as: 'borrow_update'
  post '/borrow_request/:id', to: 'borrow_requests#make_chatroom', as: 'borrow_chatroom'

  resources :notifications do
    collection do
      post :mark_as_read
    end
  end

  root 'home#index'
end

app/models/listing.rb
class Listing < ActiveRecord::Base
  attr_accessor
  belongs_to :user
  # TODO: depreciate lsiitng_image controller, move to ActiveStorage
  has_many :listing_images, dependent: :destroy
  has_many :comments, as: :reply
  has_many_attached :images
  has_many :borrow_requests, dependent: :destroy
  validates :title, presence: true, length: {maximum: 50}
  validates :address, presence: true
  validates :description, presence: true, length: {minimum: 5, maximum: 500}
  validates :category, presence: true
  # validate :validateTimings
  validate :image_type
  validate :check_address

  #For filtering a listing based on their category
  scope :has_category, -> (category) { where category: category }

  def validateTimings
    if self.start_lending < Date.today
      errors[:base] << "Start Time cannot be in the past"
    end
    if self.start_lending && self.end_lending && self.start_lending > self.end_lending
      errors[:base] << "Start Time must be before End Time"
    end
  end

def thumbnail image_index
  return self.images[image_index].variant(resize: '300x300').processed
end

private
 def image_type
   if images.attached? == false
     errors.add(:images, "are missing!")
   end

   images.each do |image|
     if !image.content_type.in?(%('image/jpeg image/png'))
       errors.add(:images, "needs to be JPEG or PNG")
     end
   end
 end

 def check_address
  results = Geocoder.search(self.address)
  if !results.first  #If location is invalid
    errors.add(:address, "- Meetup Address is invalid. Please try again.")
  end
 end
end

# == Schema Information
#
# Table name: create_listings
#
# t.string :"title"
# t.text :"description"
# t.text :"category"
# t.integer :"price_per_day"
# t.datetime :"start_lending"
# t.datetime :"end_lending"

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :verify_logged_in_user, except: [:search_listings, :autocomplete_listings]
  before_action :find_user
  #before_action :verify_correct_user, only: [:edit,:update]
  before_action :force_json, only: :autocomplete_listings

  def index
    if params[:filter].present?
      if params[:filter] != "All"
        @listings = Listing.has_category(params[:filter])
      else
        @listings = Listing.all
      end
    else
      @listings = Listing.all
    end
  end

  def new
    #@listing = Listing.new
    @listing = current_user.listings.build
  end

  def create
    #render plain: params[:listing].inspect
    #@listing = Listing.new(listing_params)
    @listing = current_user.listings.build(listing_params)
    results = Geocoder.search(@listing.address)
    if !results.first  #If location is invalid
      flash[:error] = "Can't find location"
    else
      @listing.latitude = results.first.coordinates[0]
      @listing.longitude = results.first.coordinates[1]
    end
    if @listing.save
      flash[:notice] = "Listing was successfully created"
      redirect_to listing_path(@listing)
    else
      puts @listing.errors.full_messages
      render 'new'
    end
  end

  def show
    @listing = Listing.find(params[:id])
  end

  def edit
    @listing = Listing.find(params[:id])
  end

  def update
    @listing = Listing.find(params[:id])
    if @listing.update(listing_params)
     flash[:notice] = "Listing was updated"
     redirect_to listing_path(@listing)
    else
     flash[:notice] = "Listing was not updated"
     render 'edit'
    end
 end

  def destroy
    @listing = Listing.find(params[:id])
    @listing.images.purge
    @listing.destroy
    flash[:notice] = "Listing was deleted"
    redirect_to listings_path
  end

  def search_listings
    @listings_found = Listing.ransack(title_cont: params[:listings_q]).result(distinct: true)
  end

  def autocomplete_listings
      @listings_found = Listing.ransack(title_cont: params[:listings_q]).result(distinct: true)
        respond_to do |format|
        format.html{}
        format.json{
          @listings_found = @listings_found.limit(5)
        }
      end
  end

  def report
    if params[:id].present? and Listing.exists?(id: params[:id])
      @listing = Listing.find(params[:id])
      if Report.exists?(user_id: @current_user.id, listing_id: @listing.id)
        flash[:danger] = "You have already submitted a report for this listing"
      else
        @report = Report.new
        @report.user_id = @current_user.id
        @report.listing_id = @listing.id
        if @report.save
          flash.now[:success] = "successfully Reported this listing"
        else
          flash.now[:danger] = "Could not report this item"
        end
      end
      render 'show'
    else
      @listings = Listing.all
      render 'index'
    end
  end

 private

     def find_user
      if params[:user_id]
        puts params[:user_id]
        @user = User.find(params[:user_id])
      end
    end

    def listing_params
      params.require(:listing).permit(:title, :description, :category, :lending_range, :start_lending, :end_lending, :address,:latitude,:longitude,:address,images: [])
    end

    def parse_dates(lending_range)
      start_b = lending_range.split(" - ")[0].split("/")
      @start_l = DateTime.new(start_b[0].to_i, start_b[1].to_i, start_b[2].to_i)
      end_b = lending_range.split(" - ")[1].split("/")
      @end_l = DateTime.new(end_b[0].to_i, end_b[1].to_i, end_b[2].to_i)
      return @start_l, @end_l
    end


    #to ensure "/search_listings" is allowed as well as "/search_listings.json"
    def force_json
      request.format = :json
    end


end

app/helpers/listings_helper.rb
module ListingsHelper
	def not_listing_owner
      @current_listing = Listing.find(params[:id])
      if @current_listing.user.id == current_user.id
      	return false
      else
      	return true
      end
  end

	def is_listing_owner
    @current_listing = Listing.find(params[:id])
    if(@current_listing.user.id == current_user.id)
      return true
    else
      return false
    end
  end 

  def is_listing_owner_with_params(listing_id)
    @current_listing = Listing.find(listing_id)
    if(@current_listing.user.id == current_user.id)
      return true
    else
      return false
    end
  end

  def get_rounded_rating
    @current_listing = Listing.find(params[:id])
    if @current_listing.rating.nil?
      return 0
    else
      return @current_listing.rating.round
    end
  end

  def has_user_already_requested_to_borrow_listing
    current_listing = Listing.find(params[:id])
    if current_listing.borrow_requests.nil? || current_listing.borrow_requests.count == 0
      return true
    end

    borrow_request = current_listing.borrow_requests.where(listing_id: current_listing.id)

    if borrow_request.first.user_id == current_user.id
      return false
    else
      return true
    end
  end

end

app/views/listings/_form.html.erb
<div class="container">
  <% if @listing.errors.any? %>
  <h4>The following errors prevented the listing from saving:</h4>
  <ul>
  <% @listing.errors.full_messages.each do |message|%>
  <li><%= message%></li>
  <% end %>
  </ul>
  <% end %>

  <%= form_for @listing do |f| %>
  <p>
    <%= f.label :title, class:"font-weight-bold", style:"color:#9a00bc;", data: {toggle:"tooltip", placement:"right", title:"What's your item called? Keep it short but descriptive!"}%>
    <%= f.text_field :title, placeholder:"eg. Canon XF205" , class: 'form-control'%>
  </p>
  <p>
    <%= f.label :category, class:"font-weight-bold", style:"color:#9a00bc;", data: {toggle:"tooltip", placement:"right", title:" Select a category to increase your item's visibility to potential borrowers!"}  %>
    <%= f.select :category, ["Film & Photography","Audio Visual Equipment","Projectors & Screens","Drones","DJ Equipment","Transport","Storage","Electronics","Party & Events","Sports","Musical Instruments","Home / Office / Garden","Kids & Baby","Holiday & Travel","Clothing"] , class: 'form-control'%>
  </p>
  <p>
    <%= f.label :description, style:"color:#9a00bc;", class:"font-weight-bold",data: {toggle:"tooltip", placement:"right", title:"What is your item? Anything particular about it? This is the place to write it."} %>
    <%= f.text_area :description, placeholder:"eg. Shooting beautiful shots on film is made simple with the auto mode, but you're able to also switch that off and shoot in full manual! ", class: 'form-control'%>
  </p>
  <p>
    <%= f.label :address,  "Meetup Address: ", class:"font-weight-bold", style:"color:#9a00bc;", data: {toggle:"tooltip", placement:"right", title:"Where can this item be picked up?"}%>
    <%= f.text_field :address,placeholder:"eg. 25 St George St", class: 'form-control'%>
  </p>
  <p>
    <%= f.label :start_lending, class:"font-weight-bold", style:"color:#9a00bc;", data: {toggle:"tooltip", placement:"right", title:"When is your item available from?"} %>
    <%= f.date_select :start_lending, class: 'form-control'%>
  </p>
  <p>
    <%= f.label :end_lending, class:"font-weight-bold", style:"color:#9a00bc;" %>
    <%= f.date_select :end_lending, class: 'form-control'%>
  </p>
  <p>
    <%= f.label :image, class:"font-weight-bold", style:"color:#9a00bc;", data: {toggle:"tooltip", placement:"right", title:"Images are helpful for potential borrowers. The more the merrier!"} %>
    <%= f.file_field :images, multiple: true , class: 'form-control'%>
  </p>
  <p>
    <%= f.submit 'Create Listing', :class => "btn btn-primary w-100"%>
  </p>
  <% end %>
  <%= link_to 'Back', listings_path, :class => "btn btn-back w-100" %>
</div>

<script async src="https://maps.googleapis.com/maps/api/js?libraries=places&key=AIzaSyAG4tWx7kUqZymglhMc6mRstD_RXXTEeMY"></script>
<script src="https://ubilabs.github.io/geocomplete/jquery.geocomplete.js"></script>
<script>

$(function(){
  $("#listing_address").geocomplete()
    .bind("geocode:result", function(event, result){
      $.log("Result: " + result.formatted_address);
    })
    .bind("geocode:error", function(event, status){
      $.log("ERROR: " + status);
    })
    .bind("geocode:multiple", function(event, results){
            $.log("Multiple: " + results.length + " results found");
          });

        $("#find").click(function(){
          $("#listing_address").trigger("geocode");
        });


        $("#examples a").click(function(){
          $("#listing_address").val($(this).text()).trigger("geocode");
          return false;
        });

      });
</script>

<script>
$(function(){
  // console.log(start_lending, end_lending)
  $('[data-behavior=daterangepicker]').daterangepicker({
    minDate: moment(),
    locale: { format: 'YYYY/MM/DD'},
    cancelLabel: 'Clear'
  });
});
</script>

app/views/listings/edit.html.erb
<h1>Editing a Listing</h1>
<%= render 'form' %>

app/views/listings/index.html.erb
<div class="container-fluid">
    <!-- Top Listings Page Filter Toolbar -->
    <nav class="navbar navbar-expand-md py-3" >
		<div class="container">
		<%# mobile display toggle  %>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#listings-toolbar" aria-controls="listings-toolbar" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon w-100 d-flex flex-row">
                <p>Refine by: </p>
                <i class="material-icons">apps</i>
            </span>
		</button>
			<div class="collapse navbar-collapse" id="listings-toolbar">
				<ul class="navbar-nav">
          <li>
              <%= form_tag listings_path, :method => 'get', html: {class: "form-inline"} do %>
                  <%= select_tag :filter,
                      options_for_select(["All", "Film & Photography","Audio Visual Equipment","Projectors & Screens","Drones","DJ Equipment","Transport","Storage","Electronics","Party & Events","Sports","Musical Instruments","Home / Office / Garden","Kids & Baby","Holiday & Travel","Clothing"]),
                       class: "form-control w-100"
                       %>
                  <%= submit_tag 'Filter by Category', class: 'btn btn-outline-info mt-2' %>
              <% end %>
          </li>
    		</ul>
				<ul class="navbar-nav ml-auto">
          <li>
            <%= link_to "Create new listing", new_listing_path, class: "btn btn-outline-info mr-2" %>
  				</li>
					<li>
						<%= form_with url: search_listings_path, local: true, method: :get, html: {class: "form-inline"} do |form| %>
              <%= form.text_field :listings_q, placeholder: "Search for a listing..", data: { behaviour: "autocomplete_listings" }, class: "form-control w-100" %>
              <%= form.button "Search", class: "btn btn-outline-success" %>
            <% end %>
					</li>
				</ul>
			</div>
		</div>
	</nav>

    <div class="row mt-4" id="listingsObjectDivUniqueId">
        <% if @listings.count > 0%>
            <%= render @listings %>
        <%else%>
            <div class="col-md-12">
                <div class="card d-flex p-5 mb-5">
                    <div class="card-text p-5 d-flex justify-content-center align-items-center text-secondary">
                      No listings found
                    </div>
                </div>
            </div>
        <%end%>
    </div>
</div >

app/views/listings/new.html.erb
<div class="container-fluid bg">
    <div class="container">
      <div class="row justify-content-center">
        <h1 class="mt-2 font-weight-bold"> Create a new Listing </h1>
        <div class="col-md-12">
            <%= render 'form' %>
        </div>
      </div>
    </div>
</div>

app/views/listings/search_listings.html.erb
<div class="container-fluid">
<% if logged_in? %>
	<div class="m-4">
	<h1 class="text-center">Listings Search Results</h1>
	<% if params[:listings_q] and params[:listings_q] != "" %>
		<% if @listings_found.count > 0 %>
			<h4> Found <%= @listings_found.count %> listing(s) containing "<%= params[:listings_q] %>": </h4>
			<%= render @listings_found %> <br>
		<% else %>
			<div class="col-md-12">
					<div class="card d-flex p-5 mb-5">
						<div class="card-text p-5 justify-content-center text-center align-items-center text-secondary">
							Didn't find any mathing listings <br>
							<h5 class="modal-title font-weight-bold">Be the first one to request this item. </h5> <br>
							<h5 class="modal-title font-weight-bold"><%= link_to "Request "+params[:listings_q], new_live_search_path, class:'btn btn-outline-info h-25', data: {toggle:"modal", target:"#liveSearchModal"} %></h5>
						</div>
					</div>
			</div>
			<!-- <h3> No listings found for "<%= params[:listings_q] %>" </h3>
			<%= link_to 'Request this item!', new_live_search_path %> -->
		<% end %>
	<% end %>
	</div>
	</div>
<%# modal %>
<%= render 'live_searches/new_modal' %>
<% else %>
		<!-- Modal -->
		<div class="modal fade" id="makeSureYouSignUpModal" tabindex="-1" role="dialog" aria-labelledby="makeSureYouSignUpModalLabel" aria-hidden="true">
			<div class="modal-dialog" role="document">
				<div class="modal-content">
					<div class="modal-header">
						<h5 class="modal-title font-weight-bold" id="makeSureYouSignUpModalLabel" style="color:purple!important;">Sign up to see Listings</h5>
						<button type="button" class="close" data-dismiss="modal" aria-label="Close">
							<span aria-hidden="true">&times;</span>
						</button>
					</div>
					<div class="modal-body font-weight-bold">
					Nice! You've already started searching for listings, sign up!
					</div>
					<div class="modal-footer">
					    <%= link_to "Home", root_path ,id:"signupHomeButton",class: "btn btn-outline-primary" %>
					</div>
				</div>
			</div>
		</div>

		<script>
		     $('#makeSureYouSignUpModal').modal('show');
		</script>

<% end%>

app/views/listings/show.html.erb
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAG4tWx7kUqZymglhMc6mRstD_RXXTEeMY"></script>
<div class="container-fluid">
  <div class="container">
    <div class="row">
      <div class="col-lg-6 mb-5">
        <div class="card mt-4">
              <!-- Listing Image Carousel  -->
              <div id="carouselExampleFade" data-interval="2000" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner">
                  <% (0...@listing.images.count).each.with_index do |image, index| %>
                      <% if index == 0 %>
                        <div class="carousel-item active">
                          <%= image_tag(@listing.thumbnail(image), :class => " d-block w-100 card-img-top", :style=>"object-fit:contain;")%>
                        </div>
                      <% else %>
                        <div class="carousel-item">
                          <%= image_tag(@listing.thumbnail(image), :class => " d-block w-100 card-img-top", :style=>"object-fit:contain;")%>
                        </div>
                      <%end%>
                    <% end %>
                </div>
                <% if @listing.images.count > 1%>
                  <a class="carousel-control-prev" href="#carouselExampleFade" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                  </a>
                  <a class="carousel-control-next" href="#carouselExampleFade" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                  </a>
                <% end %>
              </div>
            <!-- Listing rating -->
            <div class="card-body pb-3">
                <p class="card-text"> Average Rating:</p>
                <p class="card-text">
                  <% if get_rounded_rating == 0 %>
                      <p class="card-text"> No ratings yet </p>
                  <% else %>
                    <% for i in 1..get_rounded_rating do %>
                      <i class="material-icons" style="color:#f2a900!important;">
                      grade
                      </i>
                    <%end%>
                  <% end %>
                </p>
              </div>
          </div>
          <!--  For adding a review -->
          <%if !is_listing_owner %>
            <div class="card mt-2">
              <div class="card-header">Review this Item:</div>
              <div class="card text p-3">
              <%= form_for [@listing, Comment.new], class:"form-control" do |f| %>
                    <%= f.text_area :body, placeholder: "Add a comment", class:'form-group' %><br/>
                    <%= f.hidden_field :rating %>
                    <div id="stars-rating" clicked-value="0">
                      <i class="material-icons star-rating" id="star-rating-1" star-value="1">grade</i> <i class="material-icons star-rating" id="star-rating-2" star-value="2">grade</i> <i class="material-icons star-rating" id="star-rating-3" star-value="3">grade</i> <i class="material-icons star-rating" id="star-rating-4" star-value="4">grade</i> <i class="material-icons star-rating" id="star-rating-1" star-value="5">grade</i>
                    </div>
                    <%= f.submit "Add Comment", class:'btn btn-outline-info mt-2' %>
                  <% end %>
              </div>
            </div>
          <%end%>
        <!-- Showing existing comments on the post  -->
        <%= render(partial: 'comments/comment', collection: @listing.comments) %>
      </div>

      <!-- Second Half of the listing show page -->
      <div class="col-lg-6 justify-content-center">
      <!-- Responsive way to center the title of the listing -->
        <div class="row">
            <div class="col-md-3">
            </div>
            <div class="col-md-6">
              <h1 class="font-weight-bold text-center mt-5"><%= @listing.title %> </h1>
            </div>
            <div class="col-md-3">
               <span class="badge badge-pill mt-5"><%= @listing.category %> </span>
            </div>
        </div>
          <h4 class="my-2 font-weight-bold text-secondary text-center"> <%= @listing.description %> </h4>
          <%if not_listing_owner  && has_user_already_requested_to_borrow_listing%>
              <div class="card align-items-center mt-4">
                <div class="card-body">
                    <p class="mt-3 mb-4 font-weight-bold" style="color:#9a00bc;">When do you want this?</p>
                    <div id='listing_start_date' style="display: none"><%if @listing %><%= @listing.start_lending%><%else%><%="N/A"%><%end%></div>
                    <div id='listing_end_date' style="display: none"><%if @listing %><%= @listing.end_lending%><%else%><%="N/A"%><%end%></div>
                      <%= form_for(:borrow_request, class: "form-control", url: create_borrow_request_path(@listing), method: :get) do |form| %>
                      <%= form.text_field :date_range, class: "daterange", data:{ behavior: 'daterangepicker' } %>
                      <br />
                      <%= submit_tag "Request Item", class: 'btn db-browse-btn ml-4 mt-4 font-weight-bold', style:"color:white!important;" %>
                      <% end %>
                </div>
              </div>
          <%end%>
        <div class="row justify-content-center">
          <% if @listing.user_id == current_user.id %>
              <%= button_to "Edit", edit_listing_path(@listing), class: 'btn btn-outline-info', :method => :get%>
         <%end%>
        </div>
        <div class="row justify-content-center">
          <h5 class="mt-3 font-weight-bold"> Who's lending this out? </h5>
        </div>
        <div class="row justify-content-center">
              <h5 class="mt-2 font-weight-bold"> <%= @listing.user.name %> </h5>
        </div>
         <div class="d-flex flex-row ml-3 justify-content-center">
                <h6 class="font-weight-bold text-secondary mb-3">Rating:</h6>
                <h6 class="ml-3 font-weight-bold">
                    <% if get_rounded_user_rating(@listing.user_id) == 0 %>
                        <p class="card-text"> No ratings yet </p>
                    <% else %>
                        <% for i in 1..get_rounded_user_rating(@listing.user_id) do %>
                        <i class="material-icons" style="color:#f2a900!important;">
                        grade
                        </i>
                        <%end%>
                    <% end %>
                 </h6>

        </div>
        <div class="row justify-content-center">
         <button type="button" class="btn db-create-btn font-weight-bold my-1" style="color:white!important;" data-toggle="modal" data-target="#listingUserReviewsModal">
                    See <%= @listing.user.name%>'s Reviews
                </button>
        </div>

        <div class="row justify-content-center">
          <%if @listing.user.person.image.attachment != nil and @listing.user.person.image.content_type.in?(%('image/jpeg image/png')) %>
          <%= image_tag(@listing.user.thumbnail, :class => "img-thumbnail my-3")%>
          <% else %>
          <%= image_tag("empty-user-icon.png", :class => "img-thumbnail my-3") %>
          <%end%>
        </div>

        <div class="row justify-content-center">
              <%= button_to "View Profile", user_path(@listing.user),params: {active_tab: "dashboardTab"}, class:"btn btn-primary", :method => :get %>
        </div>

        <div id='user-lat' style="display: none"><%if @listing %><%= @listing.latitude%><%else%><%="N/A"%><%end%></div>
        <div id='user-long' style="display: none"><%if @listing %><%= @listing.longitude%><%else%><%="N/A"%><%end%></div>
        <%if @listing.latitude and @listing.longitude and @listing.address %> <!-- If listing location is valid-->
          <br><p class="card-text"> Meetup Location:<br><%= @listing.address %></p>
          <div id="user_map"></div>
        <% end %>

        <div class="row justify-content-center">
          <% if !is_listing_owner%>
                <%= link_to "Report this listing", report_listing_path(@listing), class: 'btn btn-danger btn-outline-info mt-2', data: {toggle:"tooltip", placement:"right", title:"Report this listing if you find inappropriate, offensive, or irrelevant content. Our admin will then review the listing and take further action."}%>
          <%end%>
        </div>
      </div>

     </div>
   </div>


</div>

<style>
  #user_map {
    width: 100%;
    height: 200px;
  }
</style>

<script>
  var latitude = document.getElementById("user-lat").innerHTML;
  var longitude = document.getElementById("user-long").innerHTML;

  if (latitude == "N/A" || longitude == "N/A")
  {
    alert("Refresh the page to update your location again!");
  }
  else
  {
    var map = new GMaps({
      div: '#user_map',
      lat: latitude,
      lng: longitude
    });

    map.addMarker({
        lat: latitude,
        lng: longitude,
        title: 'My Location',
        click: function(e) {
          alert('My location is at [' + latitude + ', '+longitude+']');
        }
    });
  }
</script>

<script>

$(function(){
  var start_lending = document.getElementById("listing_start_date").innerHTML.split(' ')[0];
  var end_lending = document.getElementById("listing_end_date").innerHTML.split(' ')[0];
  // console.log(start_lending, end_lending)
  // For some reason when i do -1 it shows up all of the dates
  $('[data-behavior=daterangepicker]').daterangepicker({
    startDate: start_lending,
    minDate: start_lending,
    endDate: end_lending,
    maxDate: end_lending,
    locale: { format: 'YYYY/MM/DD'},
    cancelLabel: 'Clear'
  });

  // $('[data-behavior=daterangepicker]').on('cancel.daterangepicker', function(){
  //   $(this).val(' ');
  // });

});
</script>



<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
              <div class="modal-content">
                <div class="modal-body">
                 You've sucessfuly requested this item? What next?
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                  <button type="button" class="btn btn-primary">Save changes</button>
                </div>
              </div>
            </div>
        </div>



<div class="modal fade" id="listingUserReviewsModal" tabindex="-1" role="dialog" aria-labelledby="listingUserReviewsModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="listingUserReviewsModalLabel"><%= @user.name%>'s Reviews</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" style="overflow-y:scroll;">
        <%if @user.person.comments.count == 0%>
        No reviews yet
        <%else %>
          <%= render(partial: 'comments/comment', collection: @user.person.comments) %>
        <%end%>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>