config/routes.rb
Rails.application.routes.draw do
  resources :live_searches
  get 'groups/index'
  get 'groups/show'
  post 'groups/show'
  get 'groups/new'
  post 'groups/join'
  post 'groups/leave'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  get 'contact_us/index'
  get 'users/new'
  get 'privacy_policy/index'
  get 'terms_of_service/index'
  get 'about/index'

  #get '/borrow_reauests'
  get 'home/index'

  # Session routes
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # Users routes
  resources :users do
    resources :settings , only: [:index, :destroy]
    resources :password_changes, only: [:new, :create]
  end

  #Review routes
  resources :people do
    resources :comments
  end
  resources :users do
    resources :comments
  end

  resources :listings do
    resources :comments
  end
  resources :comments do
    resources :comments
  end

  #Private messaging routes
  mount ActionCable.server => '/cable'

  resources :chatrooms
  resources :messages

  # Account Activation routes
  resources :account_activations, only: [:edit]

  # Password Reset Routes
  resources :password_resets, only: [:new,:create,:edit,:update]

  # Listing routes
  resources :listings

  # Groups routes
  resources :groups
  get :join, controller: :groups
  get :leave, controller: :groups
  post '/groups/join', to: 'group#join'
  post '/groups/leave', to: 'group#leave'

  # Search routes
  get :autocomplete_users, controller: :users
  get :autocomplete_listings, controller: :listings
  get :autocomplete_groups, controller: :groups
  get :autocomplete_add_to_groups, controller: :groups
  get '/search_users', to: 'users#search_users'
  get '/search_listings', to: 'listings#search_listings'
  get '/search_groups', to: 'groups#search_groups'
  get '/search_add_to_groups', to: 'groups#search_add_to_groups'
  get '/add_to_group/:user_id', to: 'groups#add_to_group', as: 'add_to_group'

  # Location routes
  resources :locations

  # Report routes (for listings)
  get '/listings/:id/report', to: 'listings#report', as: 'report_listing'
  get '/reports/delete_listing_and_request/:id', to: 'reports#delete_listing_and_request', as: 'delete_report_listing'
  get '/reports/delete_request/:id', to: 'reports#delete_request', as: 'delete_report_request'

  # Report routes (for users)
  get '/users/:id/report', to: 'users#report', as: 'report_user'
  get '/user_report/delete_request/:id', to: 'user_report#delete_request', as: 'delete_user_report_request'

  # resources :borrow_requests
  # get :requested_listings, controller: :borrow_requests
  # get :need_approval, controller: :borrow_requests

  get '/borrow_requests/:listing_id', to: 'borrow_requests#send_request', as: 'create_borrow_request'
  patch 'borrow_request/:id', to: 'borrow_requests#approve', as: 'borrow_approve'
  get '/borrow_request/:id', to: 'borrow_requests#decline', as: 'borrow_decline'
  delete '/borrow_request/:id', to: 'borrow_requests#delete_request', as: 'borrow_delete'
  put '/borrow_request/:id', to: 'borrow_requests#update', as: 'borrow_update'
  post '/borrow_request/:id', to: 'borrow_requests#make_chatroom', as: 'borrow_chatroom'

  resources :notifications do
    collection do
      post :mark_as_read
    end
  end

  root 'home#index'
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :memberships, :dependent => :delete_all 
  has_many :users, through: :memberships, :dependent => :delete_all 
  
  validates :name, presence: true, length: {minimum: 5}
  validates :description, presence: true, length: {minimum: 5, maximum: 1000}
  validates :isPublic, presence: true
    
  def member_exists(user)
    exists = false
    Membership.all.each do |membership|
      if membership.group_id == self.id and membership.user_id == user.id
        exists = true
      end
    end
    exists
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :verify_logged_in_user
  before_action :force_json, only: [:autocomplete_groups, :autocomplete_add_to_groups]


  def index
    @groups = Group.all
  end

  def show
    @group = Group.find(params[:id])
    @@shown_group = Group.find(params[:id])
  end

  def new
    @group = current_user.groups.new
  end
  
  def create
    @group = current_user.groups.create(group_params_validator)
    @group.owner_id = current_user.id
    
    if @group.save 
      flash[:success] = "Your new group is successfully created"
      redirect_to group_path(@group)
    else
      render 'new'
    end
  end
  
  def destroy
    if Group.where(id:params[:id]).count != 0
      @group = Group.find(params[:id])
      @group_users = @group.users
      @group_users.destroy
      @group.destroy
      flash[:success] = "Group has been successfully deleted"
    else
      flash[:danger] = "Group ID not found"
    end
    redirect_to groups_path 
  end
  
  def join
    @group = Group.find(params[:group])
    @user = User.find(params[:user])
    @membership = Membership.new
    @membership.group_id = @group.id
    @membership.user_id = @user.id
    if @membership.save
      # Send a notification to everyone in the group member
      @group.users.each do |current_group_member|
        if not current_group_member.id == current_user.id
          if current_group_member.id == @group.owner_id
            @notif_recipient = User.find(@group.owner_id)
            #Send notification to the group owner
            @new_notif = Notification.new(recipient: @notif_recipient, actor_id: current_user.id ,action: "join_group_owner",notifiable: @group)
          else
            @notif_recipient = User.find(current_group_member.id)
            # Send notification to all the group members in the group
            @new_notif = Notification.new(recipient: @notif_recipient, actor_id: current_user.id ,action: "join_group_member",notifiable: @group)
          end
          @new_notif.save
        end
      end

      flash[:success] = "Successfully joined the '#{@group.name}' group"
    else
      flash[:error] = "Couldn't join the '#{@group.name}' group"
    end
    redirect_to groups_path
  end
  
  def leave
    @group = Group.find(params[:group])
    @user = User.find(params[:user])
    @membership= Membership.find_by(user_id: @user.id, group_id: @group.id)
    if @membership.destroy
      @group.users.each do |current_group_member|
        if not current_group_member.id == current_user.id
          @notif_recipient = User.find(current_group_member.id)
          @new_notif = Notification.new(recipient: @notif_recipient, actor_id: current_user.id ,action: "leave_group",notifiable: @group)
          @new_notif.save
        end
      end

      flash[:success] = "Successfully left the '#{@group.name}' group"
    else
      flash[:error] = "Couldn't leave the '#{@group.name}' group"
    end
    redirect_to groups_path
  end
  
  def search_groups
    @groups_found = Group.ransack(name_cont: params[:groups_q]).result(distinct: true)
  end

  def autocomplete_groups
      @groups_found = Group.ransack(name_cont: params[:groups_q]).result(distinct: true)
        respond_to do |format|
        format.html{}
        format.json{
          @groups_found = @groups_found.limit(5)
        }
      end
  end
  
  def autocomplete_add_to_groups
      @add_to_groups_found = User.ransack(name_cont: params[:add_to_groups_q]).result(distinct: true)
        respond_to do |format|
        format.html{}
        format.json{
          @add_to_groups_found = @add_to_groups_found.limit(5)
        }
      end
  end
  
  def search_add_to_groups
      @add_to_groups_found = User.ransack(name_cont: params[:add_to_groups_q]).result(distinct: true)
      @target_group = @@shown_group
  end
  
  def add_to_group
    @user_id = params[:user_id]
    @user = User.find(@user_id)
    @target_group = @@shown_group
    if !@target_group.member_exists(@user)
      @membership = Membership.new
      @membership.group_id = @target_group.id
      @membership.user_id = @user_id
      if @membership.save
        @new_notif = Notification.new(recipient: @user, actor_id: current_user.id ,action: "add_group_member",notifiable: @target_group)
        @new_notif.save 
        flash[:success] = "Successfully added '#{@user.name}' to the '#{@target_group.name}' group"
      else
        flash[:error] = "Couldn't add '#{@user.name}' to the '#{@target_group.name}' group"
      end
    else
      flash[:error] = "'#{@user.name}' is already a member of the '#{@target_group.name}' group"
    end
      redirect_to group_path(@target_group)
  end
  
  private
  def group_params_validator
    params.require(:group).permit(:name, :description, :isPublic,:owner_id)
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<% if @group.errors.any? %>
	<h4>The following errors prevented the group from being created:</h4>
	<ul>
		<% @group.errors.full_messages.each do |message|%>
			<li><%= message%></li>
		<% end %>
	</ul>
<% end %>

<%= form_for @group do |f| %>
	<p>
		<%= f.label :name, style:"color:#9a00bc;", class:"font-weight-bold" %>
		<%= f.text_field :name, placeholder:"eg. Friends, Colleagues", class: 'form-control' %>
	</p>
 	<p>
		<%= f.label :description, style:"color:#9a00bc;", class:"font-weight-bold"%>
		<%= f.text_area :description, placeholder:"eg. A group of trusted friends", class: 'form-control' %>
 	</p>
 	<p>
		<%= f.label :isPublic, "Make the group public" %>
		<%= f.select :isPublic, ["No", "Yes"], :selected => "No", class: 'form-control' %>

 	</p>
	<p>
		<%= f.submit 'Create Group', :class => "btn btn-outline-info w-100" %>
	</p>
<% end %>

<%= link_to 'Back', user_path(@current_user,active_tab: "dashboardTab"), :class => "btn btn-back w-100"  %>

app/views/groups/_group.html.erb
<div class="card user-group">
  <div class="card-body">
		<h5 class="card-title font-weight-bold" style="color:purple;"><%= group.name %></h5>
		<!--<p class="card-text font-weight-bold text-secondary">Privacy: <% if group.isPublic %>Public<% else %>Private<%end%></p>-->
    	<!--<p class="card-text font-weight-bold"> Description: </p>-->
    	<p class="card-text "> 	<%= group.description %> </p>
		
		<div class="d-flex flex-row">
				<p class="card-text mr-2"><%= button_to "View Group", group_path(group), class:"card-link btn btn-primary", :method => :get %></p>	
			<% if !group.member_exists(current_user) %>
				<p class="card-text mr-2"><%= button_to "Join Group", {:controller => "group", :action => "join", :group => group, :user => current_user }, :method => :post, class:"card-link btn btn-success" %></p>
			<% else %>
				<p class="card-text mr-2"><%= button_to "Leave Group", {:controller => "group", :action => "leave", :group => group, :user => current_user }, :method => :post, class:"card-link btn btn-warning" %></p>
			<% end %>
			<% if current_user.admin? or current_user.id == group.owner_id %>
				<%= button_to 'DELETE', group, method: :delete, data: {confirm: "Are You sure you want to delete #{group.name}? "},
				class: "card-link btn btn-danger ml-2" %>
			<% end %>
		</div>
	
  </div>
</div>

app/views/groups/add_to_group.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<h1>Add user to group</h1>
		</div>
	</div>
</div>

app/views/groups/index.html.erb
<div class="container-fluid">
	<!-- Tabs for organizing groups-->
	<div class="row">
		<div class="col-md-12 p-3">
			<ul class="nav nav-tabs nav-justified">
				<li class="nav-item active">
					<a class="nav-link active" data-toggle="tab" href="#allGroupsTab">All Groups</a>
				</li>
				<li class="nav-item active">
					<a class="nav-link" data-toggle="tab" href="#myGroupsTab">My Groups</a>
				</li>
			</ul>
		</div>
	</div>
	<!-- Tab content -->
	 <div class="row">
		<div class="col-md-12">
			<div class="tab-content">
				<div id="allGroupsTab" class="tab-pane fade show active">
					<div class="container">
					  	 <%= link_to "Create new group", new_group_path, class:'btn btn-outline-info mt-3 ml-1' %>
						 <%= form_with url: search_groups_path, local: true, method: :get, html: {class: "form-inline"} do |form| %>
						 		<%= form.text_field :groups_q, placeholder: "Search for a group..", data: { behaviour: "autocomplete_groups" }, class: "form-control mt-3 mx-2" %>
							    <%= form.button "Search", class: "btn btn-outline-success mt-3 mx-3" %>
						 <% end %>

						<h1 class="p-4 font-weight-bold"> All Groups </h1>
						<%= render @groups %>
					
					</div>
				</div>
				<div id="myGroupsTab" class="tab-pane fade">
					<div class="container">
					 <h1 class="p-4 font-weight-bold"> My Groups </h1>
            		 <%= render current_user.groups.all %>
					</div>
				</div>
			</div>
		</div>
	 </div>
</div>

app/views/groups/new.html.erb
<div class="container-fluid">
	<div class="container">
		<div class="row">
			<div class="col-md-12 mt-3">
				<h1 class="text-center font-weight-bold">Create a Group</h1>
				<%= render 'form' %>
			</div>
		</div>
	</div >
</div>

app/views/groups/search_add_to_groups.html.erb
<h1>Found <%= @add_to_groups_found.count %> matches containing "<%= params[:add_to_groups_q] %>"</h1>

<% if params[:add_to_groups_q] and params[:add_to_groups_q] != "" %>
	<% if @add_to_groups_found.count > 0 %>
		<h4> Choose a user to add to the '<%=@target_group.name %>' Group: </h4>
		<% @add_to_groups_found.each do |cur_user| %>
			<ul>
				<li>
					<h5 class="card-title"><%= cur_user.name%>
					<% if !@target_group.member_exists(cur_user) %>
						<p><%= button_to "Add to Group", add_to_group_path(cur_user.id), :method => :get, class:"btn btn-success" %></p>
					<% else %>
						<p>Is already a member</p>
					<% end %>
				</li>
			</ul>
		<% end %>
	<% else %>
		<h3> No users found for "<%= params[:add_to_groups_q] %>" </h3>
	<% end %>
<% end %>

app/views/groups/search_groups.html.erb
<h1>Groups Search Results</h1>

<% if params[:groups_q] and params[:groups_q] != "" %>
	<% if @groups_found.count > 0 %>
		<h4> Found <%= @groups_found.count %> group(s) containing "<%= params[:groups_q] %>": </h4>
		<%= render @groups_found %> <br>
	<% else %>
		<h3> No groups found for "<%= params[:groups_q] %>" </h3>
	<% end %>
<% end %>

app/views/groups/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<%= form_with url: search_add_to_groups_path, local: true, method: :get, html: {class: "form-inline"} do |form| %>
				<%= form.text_field :add_to_groups_q, placeholder: "Add users to this group..", data: { behaviour: "autocomplete_add_to_groups" }, class: "form-control mt-3 mx-2" %>
				<%= form.button "Add", class: "btn btn-outline-success mt-3 mx-3" %>
			<% end %>	
		</div>	
	</div>
	<div class="row p-3">
            <h1 class="font-weight-bold col-12 text-center" style="color:#b2003b;">  <%=@group.name%> </h1> <br>
            <h4 class="font-weight-bold col-12 text-secondary mt-2 text-center">  <%=@group.description%></h4>
	</div>
	<div class="row px-3">
		<h4 class="font-weight-bold">Who Owns this group?: <%= User.find_by(id:@group.owner_id).name %></h4>
	</div>
	<div class="row p-3">
		 <% if !@group.member_exists(current_user) %>
			<%= button_to "Join Group", {:controller => "group", :action => "join", :group => @group, :user => current_user }, :method => :post, class:"card-link btn btn-success mr-2" %>
		<% else %>
			<%= button_to "Leave Group", {:controller => "group", :action => "leave", :group => @group, :user => current_user }, :method => :post, class:"card-link btn btn-warning mr-2" %>
		<% end %>

		<% if current_user.admin? or current_user.id == @group.owner_id %>
			<%= button_to 'Delete Group', @group, method: :delete, data: {confirm: "Are You sure you want to delete #{@group.name}? "},
			class: "card-link btn btn-danger" %>
		<% end %>
	</div>
	<h4 class="font-weight-bold" style="">Group Members:</h4>	
	<div class="row">
      	<%= render @group.users , {class:"justify-content-center"}%>
	</div>
	<hr>
	<h4 class="font-weight-bold my-3">Listings offered from all the users in this group:</h4>	
	<div class="row">
		<% @group.users.each do |user|%>
			<% if user.listings %>
				<%= render user.listings %>
			<% end%>
		<% end %>
	</div>
</div>