config/routes.rb
Rails.application.routes.draw do
  resources :live_searches
  get 'groups/index'
  get 'groups/show'
  post 'groups/show'
  get 'groups/new'
  post 'groups/join'
  post 'groups/leave'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  get 'contact_us/index'
  get 'users/new'
  get 'privacy_policy/index'
  get 'terms_of_service/index'
  get 'about/index'

  #get '/borrow_reauests'
  get 'home/index'

  # Session routes
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # Users routes
  resources :users do
    resources :settings , only: [:index, :destroy]
    resources :password_changes, only: [:new, :create]
  end

  #Review routes
  resources :people do
    resources :comments
  end
  resources :users do
    resources :comments
  end

  resources :listings do
    resources :comments
  end
  resources :comments do
    resources :comments
  end

  #Private messaging routes
  mount ActionCable.server => '/cable'

  resources :chatrooms
  resources :messages

  # Account Activation routes
  resources :account_activations, only: [:edit]

  # Password Reset Routes
  resources :password_resets, only: [:new,:create,:edit,:update]

  # Listing routes
  resources :listings

  # Groups routes
  resources :groups
  get :join, controller: :groups
  get :leave, controller: :groups
  post '/groups/join', to: 'group#join'
  post '/groups/leave', to: 'group#leave'

  # Search routes
  get :autocomplete_users, controller: :users
  get :autocomplete_listings, controller: :listings
  get :autocomplete_groups, controller: :groups
  get :autocomplete_add_to_groups, controller: :groups
  get '/search_users', to: 'users#search_users'
  get '/search_listings', to: 'listings#search_listings'
  get '/search_groups', to: 'groups#search_groups'
  get '/search_add_to_groups', to: 'groups#search_add_to_groups'
  get '/add_to_group/:user_id', to: 'groups#add_to_group', as: 'add_to_group'

  # Location routes
  resources :locations

  # Report routes (for listings)
  get '/listings/:id/report', to: 'listings#report', as: 'report_listing'
  get '/reports/delete_listing_and_request/:id', to: 'reports#delete_listing_and_request', as: 'delete_report_listing'
  get '/reports/delete_request/:id', to: 'reports#delete_request', as: 'delete_report_request'

  # Report routes (for users)
  get '/users/:id/report', to: 'users#report', as: 'report_user'
  get '/user_report/delete_request/:id', to: 'user_report#delete_request', as: 'delete_user_report_request'

  # resources :borrow_requests
  # get :requested_listings, controller: :borrow_requests
  # get :need_approval, controller: :borrow_requests

  get '/borrow_requests/:listing_id', to: 'borrow_requests#send_request', as: 'create_borrow_request'
  patch 'borrow_request/:id', to: 'borrow_requests#approve', as: 'borrow_approve'
  get '/borrow_request/:id', to: 'borrow_requests#decline', as: 'borrow_decline'
  delete '/borrow_request/:id', to: 'borrow_requests#delete_request', as: 'borrow_delete'
  put '/borrow_request/:id', to: 'borrow_requests#update', as: 'borrow_update'
  post '/borrow_request/:id', to: 'borrow_requests#make_chatroom', as: 'borrow_chatroom'

  resources :notifications do
    collection do
      post :mark_as_read
    end
  end

  root 'home#index'
end

app/views/shared/_about_modal.html.erb
<div class="modal fade" id="aboutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="aboutModalLabel">About Us</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div> 
      <div class="modal-body">
	  		XChange's philosophy is based on the idea that we often purchase things that we only use once. We want to help you save clutter and money in your home by
          connecting you with the people who are willing to lend what you need. Give your items a second life or save money and reduce clutter by borrowing instead.
        <div class="our-devs mt-4">
          <div class="row mx-2 mt-5">
            <div class="col-3">
              <%= image_tag("adi.jpg")%>
            </div>
            <div class="col-9 m-auto text-left">
              The team player! He loves collaborating with his teammates and fancy hair product 
            </div>
          </div>
          <div class="row mx-1 mt-5">
            <div class="col-9 m-auto text-right">
              The problem solver! Be it backend, frontend, deployment, marriage troubles, Arash has you covered
            </div>
            <div class="col-3">
              <%= image_tag("arash.jpg")%>
            </div>
          </div>
          <div class="row mx-1 mt-5">
            <div class="col-3">
              <%= image_tag("arnav.jpg")%>
            </div>
            <div class="col-9 m-auto text-left">
              The hacker! Can find a clever solution/hack to any problem
            </div>
          </div>
          <div class="row mx-1 mt-5">
            <div class="col-9 m-auto text-right">
              Jack of all traits and the master of rails! Always thinking 10 steps ahead of everyone
            </div>
            <div class="col-3">
              <%= image_tag("peter.jpg")%>
            </div>
          </div>
          <div class="row mx-1 mt-5">
            <div class="col-3">
              <%= image_tag("maru.jpg")%>
            </div>
            <div class="col-9 m-auto text-left">
              The designer! Can be heard saying, "It has to be PERFECT and nothing else will do" very very often
            </div>
          </div>
          <div class="row mx-1 mt-5">
            <div class="col-9 m-auto text-right">
              The eye for detail! Nothing can escape KC's eye. Claims to like only frontend but secretly loves backend too.
            </div>
            <div class="col-3">
              <%= image_tag("KC.jpg")%>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_contact_us_modal.html.erb
<div class="modal fade" id="contactUsModal" tabindex="-1" role="dialog" aria-labelledby="contactUsModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="contactUsModalLabel">Contact Us</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
	  		Contact Us via email at xchange.csc444@gmail.com
        <br>
        Follow us on social media:
        <div class="text-center">
          <div class="m-auto pt-2">
            <a href="https://www.facebook.com/Xchange-343909489518466"> <%= image_tag("facebook-icon.png", :class => "social-icon")%></a>
            <a href="https://twitter.com/xchange89880614"> <%= image_tag("twitter-icon.png", :class => "social-icon")%> </a>
            <a href="https://www.instagram.com/xchange.csc444"> <%= image_tag("instagram-icon.png", :class => "social-icon")%> </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_faq_modal.html.erb
<div class="modal fade" id="faqModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="faqModalLabel">Frequently Asked Question</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
	  		<div class="text-left">
          <div class="font-weight-bold"> <span class="question">Q.</span> What do I do if the item I need is not on the listings? </div>
          <div class="answer ml-3"> You can request your own item at Wanted Items!</div>

          <div class="font-weight-bold"><span class="font-weight-bold question">Q.</span> I want to only look at my friends' listings, Can I do that?</div>
          <div class="answer ml-3"> Yes! Create your own groups with your friends and view their listings from there!</div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_privacy_modal.html.erb
<div class="modal fade" id="privacyPolicyModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="privacyPolicyModalLabel">Privacy Policy</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
	  		You trust is important to us. We take your privacy seriously, and since we are not snakes and won't sell your information :)
      </div>
    </div>
  </div>
</div>

app/views/shared/_setting_menu.html.erb
<div class="col-md-12">
    <%= link_to 'Update Your Basic Information', edit_user_path(@user) ,class:'settings_selector'%> <br>
    <%= link_to 'Change Password', new_user_password_change_path(@user)%> <br>
    <%= link_to 'Deactivate Account' , user_setting_path(@user.id,0),method: :delete, data: {confirm: "We are sad to see you leave :( Are you sure you want to delete your account? This will delete all of your information from our database. ) "  }%>
</div>

app/views/shared/_terms_modal.html.erb
<div class="modal fade" id="termsOfServiceModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="termsOfServiceModalLabel">Terms of Service</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
	  		<div class="text-left">
          <div class="main-text mb-2">By using our website, you agree to</div>
          <div class="ml-2"> 
            <span class="num font-weight-bold">1.</span> Be cool.
          </div>
          <div class="ml-2"> 
            <span class="num font-weight-bold">2.</span> Respect others, even if you don't like them.
          </div>
          <div class="ml-2"> 
            <span class="num font-weight-bold">3.</span> Don't catfish.
          </div>
          <div class="ml-2"> 
            <span class="num font-weight-bold">4.</span> Be kind.
          </div>
          <div class="ml-2"> 
            <span class="num font-weight-bold">5.</span> Sell your soul.
          </div>
        </div>
      </div>
    </div>
  </div>
</div>